on:
  pull_request:
  push:
    branches: ['**']
    tags: []
jobs:
  test-and-release:
    runs-on: ubuntu-latest
    name: Continuous integration
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'
    - name: Setup dependencies
      run: |
        npm install -g @vercel/ncc
        npm install
        ncc build index.js
    - name: Unit test
      run: npm test
    - name: Run action
      id: action
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Assertion
      run: |
        if [[ "${{ steps.action.outputs.number }}" == "" ]]; then
          echo "PR not found"
          exit 1
        fi
        echo "${{ toJson(steps.action.outputs) }}"
    - name: Commit compiled file
      if: github.ref == 'refs/heads/release'
      run: |
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git config --global user.email "shiketaudonko41@gmail.com"
        git config --global user.name "kamatama41"
        git add dist/index.js
        git commit -m 'Compile index.js'
        git push origin ${{ github.ref }}
